export {default as containsText} from './contains'
export {default as slugify} from './slugify'
export {default as tagInDoc} from './tagInDoc'
export {default as checkLogin} from './checkLogin'
export {default as getCookie} from './getCookie'